packages:
  - apps/*
  - packages/*
catalogs:
  next14:
    "@next/bundle-analyzer": ^14.2.23
    "@next/third-parties": ^14.2.23
    "next": ^14.2.23
  next15:
    "@next/bundle-analyzer": ^15.2.1
    "@next/third-parties": ^15.2.1
    "next": ^15.2.1
  react18:
    react: ^18.3.1
    react-dom: ^18.3.1
    "@types/react": ^18.3.12
    "@types/react-dom": ^18.3.1
  react19:
    react: ^19.0.0
    react-dom: ^19.0.0
    "@types/react": ^19.0.10
    "@types/react-dom": ^19.0.4
