packages:
  - apps/*
  - packages/*

catalog:
  eslint: ^9.23.0
  "next-sanity-image": ^6.1.1
  "@sanity/types": 3.80.1
  sanity: ^3.82.0
  react: ^19.0.0
  react-dom: ^19.0.0
  "@types/react": ^19.0.10
  "@types/react-dom": ^19.0.4
  "@next/bundle-analyzer": ^15.2.1
  "@next/third-parties": ^15.2.1
  "next": ^15.2.1
catalogs:
  next14:
    "@next/bundle-analyzer": ^14.2.23
    "@next/third-parties": ^14.2.23
    "next": ^14.2.23
  react18:
    react: ^18.3.1
    react-dom: ^18.3.1
    "@types/react": ^18.3.12
    "@types/react-dom": ^18.3.1
  sanity:
    sanity: ^3.82.0
    "@sanity/types": ^3.80.1
    "@sanity/cli": ^3.82.0
